"""phase2_core_crm_tables

Revision ID: 5c0453d487ec
Revises: 9cb2227418de
Create Date: 2026-09-25 19:03:49.185059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c0453d487ec'
down_revision: Union[str, Sequence[str], None] = '9cb2227418de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelines',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lead_type', sa.String(length=50), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelines_id'), 'pipelines', ['id'], unique=False)
    op.create_index(op.f('ix_pipelines_is_deleted'), 'pipelines', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_pipelines_lead_type'), 'pipelines', ['lead_type'], unique=False)
    op.create_index(op.f('ix_pipelines_name'), 'pipelines', ['name'], unique=True)
    op.create_table('candidates',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('alternate_phone', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('current_location', sa.String(length=150), nullable=True),
    sa.Column('highest_education', sa.String(length=100), nullable=True),
    sa.Column('experience_years', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('current_job_title', sa.String(length=150), nullable=True),
    sa.Column('current_company', sa.String(length=150), nullable=True),
    sa.Column('expected_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notice_period', sa.String(length=50), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('preferred_job_title', sa.String(length=150), nullable=True),
    sa.Column('preferred_location', sa.String(length=150), nullable=True),
    sa.Column('employment_status', sa.String(length=50), nullable=False),
    sa.Column('availability_status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_staff_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_assigned_staff_id'), 'candidates', ['assigned_staff_id'], unique=False)
    op.create_index(op.f('ix_candidates_city'), 'candidates', ['city'], unique=False)
    op.create_index(op.f('ix_candidates_current_job_title'), 'candidates', ['current_job_title'], unique=False)
    op.create_index(op.f('ix_candidates_current_location'), 'candidates', ['current_location'], unique=False)
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=True)
    op.create_index(op.f('ix_candidates_first_name'), 'candidates', ['first_name'], unique=False)
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.create_index(op.f('ix_candidates_is_deleted'), 'candidates', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_candidates_last_name'), 'candidates', ['last_name'], unique=False)
    op.create_index(op.f('ix_candidates_phone'), 'candidates', ['phone'], unique=False)
    op.create_index(op.f('ix_candidates_skills'), 'candidates', ['skills'], unique=False)
    op.create_index(op.f('ix_candidates_status'), 'candidates', ['status'], unique=False)
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('assigned_staff_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_assigned_staff_id'), 'companies', ['assigned_staff_id'], unique=False)
    op.create_index(op.f('ix_companies_city'), 'companies', ['city'], unique=False)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_is_deleted'), 'companies', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_index(op.f('ix_companies_status'), 'companies', ['status'], unique=False)
    op.create_table('pipeline_stages',
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_stages_id'), 'pipeline_stages', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_stages_is_deleted'), 'pipeline_stages', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_pipeline_stages_pipeline_id'), 'pipeline_stages', ['pipeline_id'], unique=False)
    op.create_table('contacts',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_company_id'), 'contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_index(op.f('ix_contacts_is_deleted'), 'contacts', ['is_deleted'], unique=False)
    op.create_table('leads',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('lead_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=True),
    sa.Column('stage_id', sa.UUID(), nullable=True),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('assigned_staff_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stage_id'], ['pipeline_stages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_assigned_staff_id'), 'leads', ['assigned_staff_id'], unique=False)
    op.create_index(op.f('ix_leads_candidate_id'), 'leads', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_leads_company_id'), 'leads', ['company_id'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_is_deleted'), 'leads', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_leads_lead_type'), 'leads', ['lead_type'], unique=False)
    op.create_index(op.f('ix_leads_next_follow_up_at'), 'leads', ['next_follow_up_at'], unique=False)
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=False)
    op.create_index(op.f('ix_leads_pipeline_id'), 'leads', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_leads_stage_id'), 'leads', ['stage_id'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('job_requirements',
    sa.Column('job_title', sa.String(length=200), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_skills', sa.Text(), nullable=True),
    sa.Column('experience_min_years', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('experience_max_years', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=False),
    sa.Column('vacancies', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('assigned_staff_id', sa.UUID(), nullable=True),
    sa.Column('opened_date', sa.Date(), nullable=True),
    sa.Column('closing_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_requirements_assigned_staff_id'), 'job_requirements', ['assigned_staff_id'], unique=False)
    op.create_index(op.f('ix_job_requirements_company_id'), 'job_requirements', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_requirements_id'), 'job_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_job_requirements_is_deleted'), 'job_requirements', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_job_requirements_job_title'), 'job_requirements', ['job_title'], unique=False)
    op.create_index(op.f('ix_job_requirements_location'), 'job_requirements', ['location'], unique=False)
    op.create_index(op.f('ix_job_requirements_required_skills'), 'job_requirements', ['required_skills'], unique=False)
    op.create_index(op.f('ix_job_requirements_status'), 'job_requirements', ['status'], unique=False)
    op.create_table('lead_assignments',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_assignments_assigned_to_id'), 'lead_assignments', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_lead_assignments_id'), 'lead_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_lead_assignments_is_deleted'), 'lead_assignments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_lead_assignments_lead_id'), 'lead_assignments', ['lead_id'], unique=False)
    op.create_table('activities',
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('related_lead_id', sa.UUID(), nullable=True),
    sa.Column('related_candidate_id', sa.UUID(), nullable=True),
    sa.Column('related_company_id', sa.UUID(), nullable=True),
    sa.Column('related_job_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['related_candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_job_id'], ['job_requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_activity_type'), 'activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_index(op.f('ix_activities_is_deleted'), 'activities', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_activities_related_candidate_id'), 'activities', ['related_candidate_id'], unique=False)
    op.create_index(op.f('ix_activities_related_company_id'), 'activities', ['related_company_id'], unique=False)
    op.create_index(op.f('ix_activities_related_job_id'), 'activities', ['related_job_id'], unique=False)
    op.create_index(op.f('ix_activities_related_lead_id'), 'activities', ['related_lead_id'], unique=False)
    op.create_index(op.f('ix_activities_user_id'), 'activities', ['user_id'], unique=False)
    op.create_table('candidate_job_matches',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interview_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.String(length=100), nullable=True),
    sa.Column('placement_status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_job_matches_candidate_id'), 'candidate_job_matches', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_job_matches_id'), 'candidate_job_matches', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_job_matches_is_deleted'), 'candidate_job_matches', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_candidate_job_matches_job_id'), 'candidate_job_matches', ['job_id'], unique=False)
    op.create_index(op.f('ix_candidate_job_matches_status'), 'candidate_job_matches', ['status'], unique=False)
    op.create_table('notes',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('related_lead_id', sa.UUID(), nullable=True),
    sa.Column('related_candidate_id', sa.UUID(), nullable=True),
    sa.Column('related_company_id', sa.UUID(), nullable=True),
    sa.Column('related_job_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_job_id'], ['job_requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_author_id'), 'notes', ['author_id'], unique=False)
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_index(op.f('ix_notes_is_deleted'), 'notes', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_notes_related_candidate_id'), 'notes', ['related_candidate_id'], unique=False)
    op.create_index(op.f('ix_notes_related_company_id'), 'notes', ['related_company_id'], unique=False)
    op.create_index(op.f('ix_notes_related_job_id'), 'notes', ['related_job_id'], unique=False)
    op.create_index(op.f('ix_notes_related_lead_id'), 'notes', ['related_lead_id'], unique=False)
    op.create_table('tasks',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_user_id', sa.UUID(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('related_lead_id', sa.UUID(), nullable=True),
    sa.Column('related_candidate_id', sa.UUID(), nullable=True),
    sa.Column('related_company_id', sa.UUID(), nullable=True),
    sa.Column('related_job_id', sa.UUID(), nullable=True),
    sa.Column('reminder_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_job_id'], ['job_requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assigned_user_id'), 'tasks', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_is_deleted'), 'tasks', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_tasks_related_candidate_id'), 'tasks', ['related_candidate_id'], unique=False)
    op.create_index(op.f('ix_tasks_related_company_id'), 'tasks', ['related_company_id'], unique=False)
    op.create_index(op.f('ix_tasks_related_job_id'), 'tasks', ['related_job_id'], unique=False)
    op.create_index(op.f('ix_tasks_related_lead_id'), 'tasks', ['related_lead_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_related_lead_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_related_job_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_related_company_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_related_candidate_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_deleted'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_user_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_notes_related_lead_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_related_job_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_related_company_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_related_candidate_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_is_deleted'), table_name='notes')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_author_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_candidate_job_matches_status'), table_name='candidate_job_matches')
    op.drop_index(op.f('ix_candidate_job_matches_job_id'), table_name='candidate_job_matches')
    op.drop_index(op.f('ix_candidate_job_matches_is_deleted'), table_name='candidate_job_matches')
    op.drop_index(op.f('ix_candidate_job_matches_id'), table_name='candidate_job_matches')
    op.drop_index(op.f('ix_candidate_job_matches_candidate_id'), table_name='candidate_job_matches')
    op.drop_table('candidate_job_matches')
    op.drop_index(op.f('ix_activities_user_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_related_lead_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_related_job_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_related_company_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_related_candidate_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_is_deleted'), table_name='activities')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_type'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_lead_assignments_lead_id'), table_name='lead_assignments')
    op.drop_index(op.f('ix_lead_assignments_is_deleted'), table_name='lead_assignments')
    op.drop_index(op.f('ix_lead_assignments_id'), table_name='lead_assignments')
    op.drop_index(op.f('ix_lead_assignments_assigned_to_id'), table_name='lead_assignments')
    op.drop_table('lead_assignments')
    op.drop_index(op.f('ix_job_requirements_status'), table_name='job_requirements')
    op.drop_index(op.f('ix_job_requirements_required_skills'), table_name='job_requirements')
    op.drop_index(op.f('ix_job_requirements_location'), table_name='job_requirements')
    op.drop_index(op.f('ix_job_requirements_job_title'), table_name='job_requirements')
    op.drop_index(op.f('ix_job_requirements_is_deleted'), table_name='job_requirements')
    op.drop_index(op.f('ix_job_requirements_id'), table_name='job_requirements')
    op.drop_index(op.f('ix_job_requirements_company_id'), table_name='job_requirements')
    op.drop_index(op.f('ix_job_requirements_assigned_staff_id'), table_name='job_requirements')
    op.drop_table('job_requirements')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_stage_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_pipeline_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_index(op.f('ix_leads_next_follow_up_at'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_type'), table_name='leads')
    op.drop_index(op.f('ix_leads_is_deleted'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_company_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_candidate_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_staff_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_contacts_is_deleted'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_company_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_pipeline_stages_pipeline_id'), table_name='pipeline_stages')
    op.drop_index(op.f('ix_pipeline_stages_is_deleted'), table_name='pipeline_stages')
    op.drop_index(op.f('ix_pipeline_stages_id'), table_name='pipeline_stages')
    op.drop_table('pipeline_stages')
    op.drop_index(op.f('ix_companies_status'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_is_deleted'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_city'), table_name='companies')
    op.drop_index(op.f('ix_companies_assigned_staff_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_candidates_status'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_skills'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_phone'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_last_name'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_is_deleted'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_first_name'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_current_location'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_current_job_title'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_city'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_assigned_staff_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_pipelines_name'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_lead_type'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_is_deleted'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_id'), table_name='pipelines')
    op.drop_table('pipelines')
    # ### end Alembic commands ###
