"""phase3_courses_services_enrollments_placements_documents

Revision ID: 9fa999d48b2d
Revises: 5c0453d487ec
Create Date: 2026-09-25 19:54:09.033467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fa999d48b2d'
down_revision: Union[str, Sequence[str], None] = '5c0453d487ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_categories_id'), 'course_categories', ['id'], unique=False)
    op.create_index(op.f('ix_course_categories_is_deleted'), 'course_categories', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_course_categories_name'), 'course_categories', ['name'], unique=True)
    op.create_table('service_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_categories_id'), 'service_categories', ['id'], unique=False)
    op.create_index(op.f('ix_service_categories_is_deleted'), 'service_categories', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_service_categories_name'), 'service_categories', ['name'], unique=True)
    op.create_table('courses',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['course_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_category_id'), 'courses', ['category_id'], unique=False)
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=True)
    op.create_index(op.f('ix_courses_created_by_id'), 'courses', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index(op.f('ix_courses_is_deleted'), 'courses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_courses_name'), 'courses', ['name'], unique=False)
    op.create_index(op.f('ix_courses_status'), 'courses', ['status'], unique=False)
    op.create_table('services',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('delivery_mode', sa.String(length=50), nullable=False),
    sa.Column('fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_category_id'), 'services', ['category_id'], unique=False)
    op.create_index(op.f('ix_services_code'), 'services', ['code'], unique=True)
    op.create_index(op.f('ix_services_created_by_id'), 'services', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_is_deleted'), 'services', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=False)
    op.create_index(op.f('ix_services_status'), 'services', ['status'], unique=False)
    op.create_table('candidate_documents',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_documents_candidate_id'), 'candidate_documents', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_documents_document_type'), 'candidate_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_candidate_documents_id'), 'candidate_documents', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_documents_is_deleted'), 'candidate_documents', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_candidate_documents_uploaded_by_id'), 'candidate_documents', ['uploaded_by_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('fee_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('certificate_issued', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('progress_percentage >= 0 AND progress_percentage <= 100', name='check_enrollment_progress_percentage'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollments_candidate_id'), 'enrollments', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_enrollments_course_id'), 'enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_enrollments_created_by_id'), 'enrollments', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_enrollments_id'), 'enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_enrollments_is_deleted'), 'enrollments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_enrollments_status'), 'enrollments', ['status'], unique=False)
    op.create_table('placements',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('job_requirement_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('interview_date', sa.Date(), nullable=True),
    sa.Column('offer_date', sa.Date(), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('salary_offered', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('placement_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_requirement_id'], ['job_requirements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placements_candidate_id'), 'placements', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_placements_company_id'), 'placements', ['company_id'], unique=False)
    op.create_index(op.f('ix_placements_created_by_id'), 'placements', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_placements_id'), 'placements', ['id'], unique=False)
    op.create_index(op.f('ix_placements_is_deleted'), 'placements', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_placements_job_requirement_id'), 'placements', ['job_requirement_id'], unique=False)
    op.create_index(op.f('ix_placements_status'), 'placements', ['status'], unique=False)
    op.add_column('leads', sa.Column('course_id', sa.UUID(), nullable=True))
    op.add_column('leads', sa.Column('service_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_leads_course_id'), 'leads', ['course_id'], unique=False)
    op.create_index(op.f('ix_leads_service_id'), 'leads', ['service_id'], unique=False)
    op.create_foreign_key('fk_leads_service_id', 'leads', 'services', ['service_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_leads_course_id', 'leads', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_leads_service_id', 'leads', type_='foreignkey')
    op.drop_constraint('fk_leads_course_id', 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_service_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_course_id'), table_name='leads')
    op.drop_column('leads', 'service_id')
    op.drop_column('leads', 'course_id')
    op.drop_index(op.f('ix_placements_status'), table_name='placements')
    op.drop_index(op.f('ix_placements_job_requirement_id'), table_name='placements')
    op.drop_index(op.f('ix_placements_is_deleted'), table_name='placements')
    op.drop_index(op.f('ix_placements_id'), table_name='placements')
    op.drop_index(op.f('ix_placements_created_by_id'), table_name='placements')
    op.drop_index(op.f('ix_placements_company_id'), table_name='placements')
    op.drop_index(op.f('ix_placements_candidate_id'), table_name='placements')
    op.drop_table('placements')
    op.drop_index(op.f('ix_enrollments_status'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_is_deleted'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_created_by_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_course_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_candidate_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_candidate_documents_uploaded_by_id'), table_name='candidate_documents')
    op.drop_index(op.f('ix_candidate_documents_is_deleted'), table_name='candidate_documents')
    op.drop_index(op.f('ix_candidate_documents_id'), table_name='candidate_documents')
    op.drop_index(op.f('ix_candidate_documents_document_type'), table_name='candidate_documents')
    op.drop_index(op.f('ix_candidate_documents_candidate_id'), table_name='candidate_documents')
    op.drop_table('candidate_documents')
    op.drop_index(op.f('ix_services_status'), table_name='services')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_index(op.f('ix_services_is_deleted'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_index(op.f('ix_services_created_by_id'), table_name='services')
    op.drop_index(op.f('ix_services_code'), table_name='services')
    op.drop_index(op.f('ix_services_category_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_courses_status'), table_name='courses')
    op.drop_index(op.f('ix_courses_name'), table_name='courses')
    op.drop_index(op.f('ix_courses_is_deleted'), table_name='courses')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_created_by_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.drop_index(op.f('ix_courses_category_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_service_categories_name'), table_name='service_categories')
    op.drop_index(op.f('ix_service_categories_is_deleted'), table_name='service_categories')
    op.drop_index(op.f('ix_service_categories_id'), table_name='service_categories')
    op.drop_table('service_categories')
    op.drop_index(op.f('ix_course_categories_name'), table_name='course_categories')
    op.drop_index(op.f('ix_course_categories_is_deleted'), table_name='course_categories')
    op.drop_index(op.f('ix_course_categories_id'), table_name='course_categories')
    op.drop_table('course_categories')
    # ### end Alembic commands ###
